name: Swift Package Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: Test on iOS (Xcode 16.2)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Run xcodebuild tests (iOS)
        run: |
          DESTINATION="platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2"

          echo "Using destination: $DESTINATION"
          xcodebuild clean test \
            -scheme SVGUIView-Package \
            -destination "$DESTINATION" \
            | xcpretty
